// Copyright (c) 2026 Kinglet Language Developers
// SPDX-License-Identifier: MIT

#include "ir/lowering_op.h"

namespace kinglet {

const char *lowering_op_name(LoweringOp op) {
  switch (op) {
  case LoweringOp::Constant:
    return "Constant";
  case LoweringOp::Null:
    return "Null";
  case LoweringOp::True:
    return "True";
  case LoweringOp::False:
    return "False";
  case LoweringOp::Add:
    return "Add";
  case LoweringOp::Subtract:
    return "Subtract";
  case LoweringOp::Multiply:
    return "Multiply";
  case LoweringOp::Divide:
    return "Divide";
  case LoweringOp::Modulo:
    return "Modulo";
  case LoweringOp::Negate:
    return "Negate";
  case LoweringOp::Not:
    return "Not";
  case LoweringOp::BitNot:
    return "BitNot";
  case LoweringOp::BitAnd:
    return "BitAnd";
  case LoweringOp::BitOr:
    return "BitOr";
  case LoweringOp::BitXor:
    return "BitXor";
  case LoweringOp::Shl:
    return "Shl";
  case LoweringOp::Shr:
    return "Shr";
  case LoweringOp::LoadLocal:
    return "LoadLocal";
  case LoweringOp::LoadLocalAddr:
    return "LoadLocalAddr";
  case LoweringOp::DerefLoad:
    return "DerefLoad";
  case LoweringOp::DerefStore:
    return "DerefStore";
  case LoweringOp::StoreLocal:
    return "StoreLocal";
  case LoweringOp::Pop:
    return "Pop";
  case LoweringOp::Dup:
    return "Dup";
  case LoweringOp::CastTo:
    return "CastTo";
  case LoweringOp::FloatToBits:
    return "FloatToBits";
  case LoweringOp::BitsToFloat:
    return "BitsToFloat";
  case LoweringOp::Call:
    return "Call";
  case LoweringOp::Return:
    return "Return";
  case LoweringOp::Jmp:
    return "Jmp";
  case LoweringOp::JmpFalse:
    return "JmpFalse";
  case LoweringOp::JmpIfErr:
    return "JmpIfErr";
  case LoweringOp::Eq:
    return "Eq";
  case LoweringOp::Neq:
    return "Neq";
  case LoweringOp::Lt:
    return "Lt";
  case LoweringOp::Gt:
    return "Gt";
  case LoweringOp::Le:
    return "Le";
  case LoweringOp::Ge:
    return "Ge";
  case LoweringOp::NativeOut:
    return "NativeOut";
  case LoweringOp::NativeOutLn:
    return "NativeOutLn";
  case LoweringOp::NativeErr:
    return "NativeErr";
  case LoweringOp::NativeErrLn:
    return "NativeErrLn";
  case LoweringOp::NativeIn:
    return "NativeIn";
  case LoweringOp::NativeInSecret:
    return "NativeInSecret";
  case LoweringOp::NativeFsRead:
    return "NativeFsRead";
  case LoweringOp::NativeFsWrite:
    return "NativeFsWrite";
  case LoweringOp::NativeFsListdir:
    return "NativeFsListdir";
  case LoweringOp::NativeSysArgs:
    return "NativeSysArgs";
  case LoweringOp::StructNew:
    return "StructNew";
  case LoweringOp::BorrowFieldMut:
    return "BorrowFieldMut";
  case LoweringOp::FieldGet:
    return "FieldGet";
  case LoweringOp::FieldSet:
    return "FieldSet";
  case LoweringOp::EnumVariant:
    return "EnumVariant";
  case LoweringOp::ArrayNew:
    return "ArrayNew";
  case LoweringOp::IndexGet:
    return "IndexGet";
  case LoweringOp::IndexSet:
    return "IndexSet";
  case LoweringOp::ArrayLen:
    return "ArrayLen";
  case LoweringOp::ArrayPush:
    return "ArrayPush";
  case LoweringOp::ArrayResize:
    return "ArrayResize";
  case LoweringOp::ArrayPop:
    return "ArrayPop";
  case LoweringOp::ArrayRemove:
    return "ArrayRemove";
  case LoweringOp::ArrayContains:
    return "ArrayContains";
  case LoweringOp::ArrayClear:
    return "ArrayClear";
  case LoweringOp::ArrayInsert:
    return "ArrayInsert";
  case LoweringOp::ArrayIndexOf:
    return "ArrayIndexOf";
  case LoweringOp::ArraySlice:
    return "ArraySlice";
  case LoweringOp::ArrayReverse:
    return "ArrayReverse";
  case LoweringOp::StringStartsWith:
    return "StringStartsWith";
  case LoweringOp::StringEndsWith:
    return "StringEndsWith";
  case LoweringOp::StringReplace:
    return "StringReplace";
  case LoweringOp::StringSplit:
    return "StringSplit";
  case LoweringOp::StringTrim:
    return "StringTrim";
  case LoweringOp::StringToUpper:
    return "StringToUpper";
  case LoweringOp::StringToLower:
    return "StringToLower";
  case LoweringOp::EnumVariantPayload:
    return "EnumVariantPayload";
  case LoweringOp::EnumPayloadGet:
    return "EnumPayloadGet";
  case LoweringOp::MapNew:
    return "MapNew";
  case LoweringOp::MapGet:
    return "MapGet";
  case LoweringOp::MapSet:
    return "MapSet";
  case LoweringOp::MapHas:
    return "MapHas";
  case LoweringOp::MapRemove:
    return "MapRemove";
  case LoweringOp::MapKeys:
    return "MapKeys";
  case LoweringOp::MapLen:
    return "MapLen";
  case LoweringOp::PushHandler:
    return "PushHandler";
  case LoweringOp::PopHandler:
    return "PopHandler";
  case LoweringOp::PropagateErr:
    return "PropagateErr";
  case LoweringOp::IsNull:
    return "IsNull";
  case LoweringOp::StringToInt:
    return "StringToInt";
  case LoweringOp::StringToFloat:
    return "StringToFloat";
  case LoweringOp::StringCode:
    return "StringCode";
  case LoweringOp::StringCodeAt:
    return "StringCodeAt";
  case LoweringOp::AddI32:
    return "AddI32";
  case LoweringOp::SubtractI32:
    return "SubtractI32";
  case LoweringOp::MultiplyI32:
    return "MultiplyI32";
  case LoweringOp::DivideI32:
    return "DivideI32";
  case LoweringOp::ModuloI32:
    return "ModuloI32";
  case LoweringOp::DenseArrayNew:
    return "DenseArrayNew";
  case LoweringOp::BorrowIndexMut:
    return "BorrowIndexMut";
  case LoweringOp::Drop:
    return "Drop";
  }
  return "Unknown";
}

} // namespace kinglet
